apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Kisalaykisu/backstage-hackathon
    targetRevision: HEAD
    path: Day-3-K8s-ArgoCD/k8s
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
