apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: spotify/backstage:latest
          ports:
            - containerPort: 7007
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 7007
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 7007
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: APP_CONFIG_app_baseUrl
              value: "http://localhost:7007"
            - name: APP_CONFIG_backend_baseUrl
              value: "http://localhost:7007"

