apiVersion: v1
kind: Service
metadata:
  name: backstage-service
spec:
  selector:
    app: backstage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7007
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: custom-api-service
spec:
  selector:
    app: custom-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
