
name: ArgoCD Auto-Sync

on:
  push:
    branches:
      - master
    paths:
      - '**.yaml'
      - '**/Dockerfile'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Set kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Sync ArgoCD App
        run: |
          kubectl apply -f Day-4-DB-Helm-Integration/app.yaml
