apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kisalaykisu/backstage-hackathon.git
    targetRevision: HEAD
    path: Day-4-DB-Helm-Integration/helm/backstage
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
