alertmanager:
  enabled: false

pushgateway:
  enabled: true
  service:
    type: ClusterIP
    port: 9091

server:
  enabled: true
  service:
    type: ClusterIP
    port: 9090
  global:
    scrape_interval: 15s
    evaluation_interval: 15s
  scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']
    - job_name: 'node'
      static_configs:
        - targets: ['node-exporter:9100']
    - job_name: 'pushgateway'
      static_configs:
        - targets: ['prometheus-pushgateway:9091']
