apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
data:
  password: Z2hwX3lvdXJQQVR2YWx1ZQ==
  username: eW91ckdpdEh1YlVzZXJuYW1l



